config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  root to: 'homes#top'
  


  # ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  # 会員
  scope module: :public do #URLにpublicを含まない

  get 'homes/about' => 'homes#about'
  get '/search', to: 'searches#search'
  get 'customers/confirm' => "customers#confirm"
  patch 'customers/out' => "customers#out"
  resources :customers, only: [:index, :show, :edit, :update] do
      member do
    # いいねした一覧
    get :liked_posts
    end

    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"

  end

  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do

    resource :favorites, only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]

  end

  end



  #管理者
  namespace :admin do #URLにadminを含む
    
  get '/search', to: 'searches#search'
  root to: 'customers#index'
  patch 'customers/:id/out' => 'customers#out', as: 'customers_out'
  resources :customers, only: [:index, :show]
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do


    resources :post_comments, only: [:destroy]

  end

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed

  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower
  
  #文字制限　最小２文字、最大20字まで
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true


  #ゲスト用メールアドレス
  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end


  def guest_customer?
    email == GUEST_CUSTOMER_EMAIL
  end


  # 指定したユーザーをフォローする
  def follow(customer)
    active_relationships.create(followed_id: customer.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(customer)
    active_relationships.find_by(followed_id: customer.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(customer)
    followings.include?(customer)
  end


  # プロフィール画像を取得 (画像がない場合はno_imageアイコンを使用)
  has_one_attached :profile_image

 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
 end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page], )
    @customer = current_customer
  end

  def show
    @customer = Customer.find(params[:id])
    @post_images = @customer.post_images.page(params[:page])
  end


  def edit
  end


  def out
    @customer = Customer.find(params[:id])

    if @customer.guest_customer?　　　　　# ゲストユーザーは退会できなよう設定
      redirect_to admin_customers_path, notice: 'ゲストユーザーは退会できません。'
    else
      @customer.update(is_deleted: true) # または必要な更新処理を実行
      redirect_to admin_customers_path, notice: 'アカウントが停止しました'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :profile_image)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>プロフィール画像</th>
      <th>ユーザーネーム</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% customers.each do |customer| %>
      <tr>

        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= image_tag customer.get_profile_image(100,100) %>
          <% end %>
        </td>

        <td><%= customer.name %></td>

        <!--ゲストユーザーの場合はフォローボタンを表示しない-->
        <% if current_admin || current_customer.guest_customer? %>
        <% else %>
        <td><%= render "public/relationships/btn", customer: customer %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
              <!--ページネーション-->
             <div class="d-flex justify-content-center">
                <%= paginate @records %>
             </div>

app/views/admin/customers/edit.html.erb
<h1>Admin::Customers#edit</h1>
<p>Find me in app/views/admin/customers/edit.html.erb</p>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">


      <h2 class="mt-5" style="text-align: center">ユーザー　一覧</h2>
      <table class="table">
      
       <thead>
        <tr>
      
            <th>プロフィール画像</th>
            <th>ユーザーネーム</th>
            <th colspan="3"></th>
      
        </tr>
       </thead>
      
        <tbody>
         <% @customers.each do |customer| %>
          
          <tr>
           
          <td><%= image_tag customer.get_profile_image(100,100) %></td>
            <td><%= customer.name %></td>
            <td><%= link_to '詳細', admin_customer_path(customer.id) %></td>
      
          </tr>
          
         <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>

      <!--ページネーション-->
      <div class="d-flex justify-content-center">
        <%= paginate @customers %>
      </div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>


      <!-- ユーザーの詳細 -->
      <table class='table border rounded m-5 mx-auto', style="text-align: center">
        <tr>
          <th class="mx-auto"style="width: 150px;">
            <%= image_tag @customer.get_profile_image(100, 100) %>
            <h4>ユーザー名</h4>
            <p><%= @customer.name %></p>
          </th>
        </tr>
      </table>

      <!--<div style="text-align: center">-->
      <!--  <%#= link_to "プロフィール編集", edit_customer_path, class: "btn btn-outline-secondary" %>-->
      <!--</div>-->


      <div style="text-align: center", class="mt-3">
        <%= link_to "アカウントを停止する(強制退会)", admin_customers_out_path, method: :patch, :class => "btn btn-danger", data: { confirm: "本当にアカウントを停止しますか？" }  %>
      </div>

        <!-- ユーザーの投稿一覧 -->
        <h2 style="margin-top: 50px; text-align: center">ユーザーの投稿</h2>

        <% @post_images.each do |post_image| %>
        <div class="border rounded p-5 m-5", style="text-align: center; background-color: white;">
          <%= link_to admin_post_image_path(post_image.id) do %>
            <%= image_tag post_image.get_image , style: 'max-width: 300px; max-height:200px;' %>
          <% end %>
          <p>タイトル：<%= post_image.title %></p>
          <p>内容：<%= post_image.body %></p>
        </div>
        <% end %>
        
        <!--ページネーション-->
             <div class="d-flex justify-content-center">
                <%= paginate @post_images %>
             </div>



    </div>
  </div>
</div>