config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  root to: 'homes#top'
  


  # ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  # 会員
  scope module: :public do #URLにpublicを含まない

  get 'homes/about' => 'homes#about'
  get '/search', to: 'searches#search'
  get 'customers/confirm' => "customers#confirm"
  patch 'customers/out' => "customers#out"
  resources :customers, only: [:index, :show, :edit, :update] do
      member do
    # いいねした一覧
    get :liked_posts
    end

    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"

  end

  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do

    resource :favorites, only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]

  end

  end



  #管理者
  namespace :admin do #URLにadminを含む
    
  get '/search', to: 'searches#search'
  root to: 'customers#index'
  patch 'customers/:id/out' => 'customers#out', as: 'customers_out'
  resources :customers, only: [:index, :show]
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do


    resources :post_comments, only: [:destroy]

  end

  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :customer
    belongs_to :post_image
    
    # 最大250文字まで
    validates :comment, presence: true, length: { maximum: 250 }
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/admin/post_comments/_form.html.erb
<%= form_with model: [post_image, post_comment] do |f| %>
                                                        <!--w-100で横幅を調整-->
  <%= f.text_area :comment, rows:'5', placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信" %>
<% end %>

app/views/admin/post_comments/_index.html.erb
<h2 class="mt-5", style="text-align: center">コメント</h2>

  <% post_image.post_comments.each do |post_comment| %>

      <%= link_to customer_path(post_comment.customer) do %>
        <h4><%= image_tag post_comment.customer.get_profile_image(50,50) %> <%= post_comment.customer.name %>
      <% end %>さん</h4>

        <p style="word-wrap: break-word;"><%= post_comment.comment %></p>
        <!--`word-wrap: break-word;`をテキストを含む要素に適用すると、
        テキストが要素の幅を超えた場合に自動的に折り返されます。-->

        <p class="mb-5" style="text-align: center"><%= link_to "コメントを削除", post_image_post_comment_path(post_image, post_comment), method: :delete, class: "btn btn-sm btn-danger float-end" %></p>

  <% end %>