config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  root to: 'homes#top'
  


  # ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  # 会員
  scope module: :public do #URLにpublicを含まない

  get 'homes/about' => 'homes#about'
  get '/search', to: 'searches#search'
  get 'customers/confirm' => "customers#confirm"
  patch 'customers/out' => "customers#out"
  resources :customers, only: [:index, :show, :edit, :update] do
      member do
    # いいねした一覧
    get :liked_posts
    end

    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"

  end

  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do

    resource :favorites, only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]

  end

  end



  #管理者
  namespace :admin do #URLにadminを含む
    
  get '/search', to: 'searches#search'
  root to: 'customers#index'
  patch 'customers/:id/out' => 'customers#out', as: 'customers_out'
  resources :customers, only: [:index, :show]
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do


    resources :post_comments, only: [:destroy]

  end

  end

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :customer
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  validates :title, presence: { message: "タイトルが入力されていません" }      #文字数最大200文字  #未入力の場合エラーメッセージを表示
  validates :body, presence: { message: "内容が入力されていません" }, length: { maximum: 200, message: "エラーメッセージ" }
  validates :image, presence: { message: "ファイルが未選択です" }
  
  has_one_attached :image
    
    
   def get_image
     unless image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg') #画像がない場合にno_imageを使用
       image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
     end
     image
   end
   
   
  def favorited_by?(customer)
    if customer
      favorites.exists?(customer_id: customer.id)
    else
      false  # もし customer が nil の場合、false を返す（または他の適切な処理を行う）
    end
  end
  
     # いいねをつけた投稿の取得
def self.liked_posts(customer, page, per_page) # 1. モデル内での操作を開始
  includes(:favorites) # 2. post_favorites テーブルを結合
    .where(favorites: { customer_id: customer.id }) # 3. ユーザーがいいねしたレコードを絞り込み
    .order(created_at: :desc) # 4. 投稿を作成日時の降順でソート
    .page(page) # 5. ページネーションのため、指定ページに表示するデータを選択
    .per(per_page) # 6. ページごとのデータ数を指定
end
  
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController

  def new

    @post_image = PostImage.new

  end

  def index
    @post_images = PostImage.page(params[:page], )
  end

  def show
    @post_image = PostImage.find(params[:id])
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    @post_image = PostImage.find(params[:id])
    @post_image.update(post_image_params)
    redirect_to admin_post_image_path(@post_image)

  end

  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to admin_post_images_path
  end

    # 投稿データのストロングパラメータ
  private

  def post_image_params
    params.require(:post_image).permit(:title, :image, :body)
  end
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/views/admin/post_images/_index.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>

        <% post_images.each do |post_image| %>
        <div class="border rounded p-5 m-5", style="background-color: white;">
          <%= link_to admin_post_image_path(post_image.id) do %>
            <%= image_tag post_image.get_image %>
          <% end %>
          <p style="word-wrap: break-word;">タイトル：<%= post_image.title %></p>
          <p style="word-wrap: break-word;">内容：<%= post_image.body %></p>
          <p>コメント数： <%= post_image.post_comments.count %></p>
          <div class=<%= "favorite-" + post_image.id.to_s %> >
          <p><%= render "public/favorites/btn", post_image: post_image %></p>
          </div>
        </div>
        <% end %>


    </div>
  </div>
</div>

                 <!--ページネーション-->
             <div class="d-flex justify-content-center">
                <%= paginate @records %>
             </div>

app/views/admin/post_images/edit.html.erb
<h1>admin編集画面</h1>

<%= form_with model: @post_image do |f| %>

  <h4>画像</h4>
  <%= f.file_field :image, placeholder: "画像", accept: "image/*" %> 

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>内容</h4>
  <%= f.text_area :body %>
  
  <%= f.submit '保存' %>
  
<% end %>

app/views/admin/post_images/index.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      
      <h2 class="mt-5" style="text-align: center">みんなの投稿</h2>

        <% @post_images.each do |post_image| %>
        <div class="border rounded p-5 m-5", style="background-color: white;">
          <%= link_to admin_post_image_path(post_image.id) do %>
            <%= image_tag post_image.get_image %>
          <% end %>
          <p style="word-wrap: break-word;">タイトル：<%= post_image.title %></p>
          <p style="word-wrap: break-word;">内容：<%= post_image.body %></p>
          <p>コメント数： <%= post_image.post_comments.count %></p>
        </div>
        <% end %>
      
      
    </div>
  </div>
</div>

      <!--ページネーション-->
      <div class="d-flex justify-content-center">
        <%= paginate @post_images %>
      </div>

app/views/admin/post_images/show.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>


      <h2 style="text-align: center">投稿詳細</h2>
      
      
      
      <div class="border rounded p-5", style="background-color: white;">
        
        <p>投稿したユーザー 
        <%= link_to admin_customer_path(@post_image.customer) do %>
        <%= image_tag @post_image.customer.get_profile_image(100,100) %> <%= @post_image.customer.name %>
        </p>
        <% end %>
        
        <%= image_tag @post_image.get_image %>
        <p>タイトル：<%= @post_image.title %></p>
        <p>内容：<%= @post_image.body %></p>
        

      
        <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
        <p>コメント数： <%= @post_image.post_comments.count %></p>

        
        
          <%#= link_to "投稿を編集する", edit_admin_post_image_path(@post_image.id), class: "btn btn-sm btn-secondary" %>
          <%= link_to "投稿を削除する", admin_post_image_path(@post_image), class: "btn btn-sm btn-danger", method: :delete %>

        
        <%= render "admin/post_comments/index", post_image: @post_image %>
            
      </div>


    </div>
  </div>
</div>