config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  root to: 'homes#top'
  


  # ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  # 会員
  scope module: :public do #URLにpublicを含まない

  get 'homes/about' => 'homes#about'
  get '/search', to: 'searches#search'
  get 'customers/confirm' => "customers#confirm"
  patch 'customers/out' => "customers#out"
  resources :customers, only: [:index, :show, :edit, :update] do
      member do
    # いいねした一覧
    get :liked_posts
    end

    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"

  end

  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do

    resource :favorites, only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]

  end

  end



  #管理者
  namespace :admin do #URLにadminを含む
    
  get '/search', to: 'searches#search'
  root to: 'customers#index'
  patch 'customers/:id/out' => 'customers#out', as: 'customers_out'
  resources :customers, only: [:index, :show]
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do


    resources :post_comments, only: [:destroy]

  end

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed

  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower
  
  #文字制限　最小２文字、最大20字まで
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true


  #ゲスト用メールアドレス
  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end


  def guest_customer?
    email == GUEST_CUSTOMER_EMAIL
  end


  # 指定したユーザーをフォローする
  def follow(customer)
    active_relationships.create(followed_id: customer.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(customer)
    active_relationships.find_by(followed_id: customer.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(customer)
    followings.include?(customer)
  end


  # プロフィール画像を取得 (画像がない場合はno_imageアイコンを使用)
  has_one_attached :profile_image

 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
 end


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post_image
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :customer
    belongs_to :post_image
    
    # 最大250文字まで
    validates :comment, presence: true, length: { maximum: 250 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :customer
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  validates :title, presence: { message: "タイトルが入力されていません" }      #文字数最大200文字  #未入力の場合エラーメッセージを表示
  validates :body, presence: { message: "内容が入力されていません" }, length: { maximum: 200, message: "エラーメッセージ" }
  validates :image, presence: { message: "ファイルが未選択です" }
  
  has_one_attached :image
    
    
   def get_image
     unless image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg') #画像がない場合にno_imageを使用
       image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
     end
     image
   end
   
   
  def favorited_by?(customer)
    if customer
      favorites.exists?(customer_id: customer.id)
    else
      false  # もし customer が nil の場合、false を返す（または他の適切な処理を行う）
    end
  end
  
     # いいねをつけた投稿の取得
def self.liked_posts(customer, page, per_page) # 1. モデル内での操作を開始
  includes(:favorites) # 2. post_favorites テーブルを結合
    .where(favorites: { customer_id: customer.id }) # 3. ユーザーがいいねしたレコードを絞り込み
    .order(created_at: :desc) # 4. 投稿を作成日時の降順でソート
    .page(page) # 5. ページネーションのため、指定ページに表示するデータを選択
    .per(per_page) # 6. ページごとのデータ数を指定
end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_admin!, if: :admin_url
   
   
   #pathに/adminが含まれている全てのページは、adminでログインしないと見ることができない
  def admin_url
    request.fullpath.include?("/admin")
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   
  def top
  end

  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  
  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    
    
            # 検索ワードが空白でないことを確認
    if @content.present?
      @records = search_for(@model, @content, @method)
    else
      # 空白の場合は何も検索せず、適切なメッセージを設定
      flash[:notice] = "検索ワードを入力してください。"
      # 何もデータを表示しないようにする
      @records = []
    end
    
    @records = search_for(@model, @content, @method)
    
    
    @records = @records.page(params[:page]) # ページごとに表示
    
  end

  private
  def search_for(model, content, method)
    # 選択したモデルがuserだったら
    if model == 'customer'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        Customer.where(name: content)
      # 選択した検索方法がが部分一致だったら
      else
        Customer.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがpostだったら
    elsif model == 'post_image'
      if method == 'perfect'
        PostImage.where(title: content)
      else
        PostImage.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_password_resets_helper.rb
module CustomPasswordResetsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mx-auto"style="width: 100%;">
  <div class='container mt-5 AnnouncementPopup_hiddenWrapper_ThDWT' style="border-top: 2px solid darkgray;">
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="mt-3">CopyRight 2023 TravelShare inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">
          <span class="logo_text ml-3">
            <i class="fa-regular fa-image"> Travel Share</i>
          </span>
        </a>
          <ul class="navbar-nav ml-auto">

        <!--管理者のヘッダー-->
        <% if admin_signed_in? %>
         <div class="row">

          <li>
            <%= link_to admin_post_images_path, class: "btn" do %>
            <i class="fa-brands fa-stack-overflow fa-solid"> 投稿一覧</i>
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path, class: "btn" do %>
            <i class="fa-solid fa-users"> ユーザー管理</i>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: "btn"  do %>
              <i class="fas fa-sign-out-alt mr-2"> ログアウト</i>
            <% end %>
          </li>
          </div>
          
          <div>
           <%= render 'admin/searches/form' %>
          </div>

          
        
        <% elsif customer_signed_in? %>

        <!--ゲストユーザーのヘッダー-->
          <% if current_customer.guest_customer? %>
          <div class="row">


          <li class="nav-item">
            <%= link_to post_images_path, class: "btn" do  %>
            <i class="fa-brands fa-stack-overflow fa-solid"> 投稿一覧</i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to customer_path(current_customer.id), class: "btn" do  %>
            <i class="fa-solid fa-user"> マイページ</i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class: "btn" do %>
            <i class="fa-solid fa-right-from-bracket"> ログアウト</i>
            <% end %>
          </li>
          </div>

          <div>
           <%= render 'public/searches/form' %>
          </div>


          </div>

          <% else %>
          <!--通常のユーザーのヘッダー-->
          <div class="row">
          <li>
            <%= link_to new_post_image_path, class: "btn" do %>
            <i class="fa-solid fa-plus"> 新規投稿</i>
            <% end %>
          </li>

          <li>
            <%= link_to post_images_path, class: "btn" do %>
            <i class="fa-brands fa-stack-overflow fa-solid"> 投稿一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to liked_posts_customer_path(current_customer), class: "btn" do %>
            <i class="fa-solid fa-heart"> いいね一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to customer_path(current_customer.id), class: "btn" do %>
            <i class="fa-solid fa-user"> マイページ</i>
            <% end %>
          </li>

          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: "btn" do %>
            <i class="fa-solid fa-right-from-bracket"> ログアウト</i>
            <% end %>
          </li>
          </div>

          <div style="margin: 0 0 0 200px;">
          <%= render 'public/searches/form' %>
          </div>

          <% end %>


        <% else %>
        <!--非ログイン時の表示-->
        <div class="row">
          <li class="nav-item">
            <%= link_to new_customer_registration_path, class: "btn" do %>
            <i class="fa-solid fa-user-plus"> 新規登録</i>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_customer_session_path, class: "btn" do %>
            <i class="fa-solid fa-right-to-bracket"> ログイン</i>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to customers_guest_sign_in_path, method: :post, class: "btn" do %>
            <i class="fa-solid fa-user"> ゲストログイン</i>
            <% end %>
          </li>

        </div>
        <% end %>

         </ul>

  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/82d7b2075d.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100" style="background-color: #f0f0f0;">
    
    <%= render 'layouts/header' %>
            
            <div class="container">
      		   <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
              <% flash.each do |key, value| %>
                <p class="alert alert-<%= key %>">
                  <%= sanitize value, tags: %w(br) %>
                </p>
              <% end %>
             </div>
          </div>
      
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    
  </body>
</html>